# Generated by Django 3.0.3 on 2020-03-02 20:02

from django.db import migrations, models
import django.db.models.deletion
import modules.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(default=modules.utils.object_id, max_length=30, unique=True)),
                ('started', models.DateTimeField(null=True)),
                ('ended', models.DateTimeField(null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'threads_thread',
            },
        ),
        migrations.CreateModel(
            name='ThreadParameterType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(default=modules.utils.object_id, max_length=30, unique=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'threads_parameter_type',
            },
        ),
        migrations.CreateModel(
            name='ThreadParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(default=modules.utils.object_id, max_length=30, unique=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='thread_parameter_thread', to='threads.Thread')),
            ],
            options={
                'db_table': 'threads_parameter',
            },
        ),
        migrations.CreateModel(
            name='ThreadNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(default=modules.utils.object_id, max_length=30, unique=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='thread_node_thread', to='threads.Thread')),
            ],
            options={
                'db_table': 'threads_node',
            },
        ),
    ]
