# Generated by Django 3.0.3 on 2020-03-04 00:15

from django.db import migrations, models
import django.db.models.deletion
import modules.utils
import sls_django.identity.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('external_id', models.CharField(default=modules.utils.object_id, max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'identity_identity',
            },
        ),
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(default=modules.utils.object_id, max_length=30, unique=True)),
                ('key', models.CharField(max_length=255, unique=True)),
                ('expires', models.DateTimeField(default=sls_django.identity.models.six_months_from_now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.Identity')),
            ],
            options={
                'db_table': 'identity_identity_authtoken',
            },
        ),
    ]
